GET http://localhost:3000/events

### Create a new event
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Novo Evento 3",
  "description": "Descrição do evento",
  "date": "2020-01-01T00:00:00.000Z",
  "price": 10.5
}

### Save the id of the created event
@eventId = {{ createEvent.response.body.id }}

### Get event by id
GET http://localhost:3000/events/{{eventId}}

### Update event by id
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "Novo Eventox",
  "description": "Descrição do evento",
  "date": "2020-01-01T00:00:00.000Z",
  "price": 10.5
}

### Delete event by id
DELETE http://localhost:3000/events/{{eventId}}


### Get spots of an event
GET http://localhost:3000/events/{{eventId}}/spots

### Save the id of the created spot
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "Spot 1"
}